window.VSR_LANGS = Object.assign(window.VSR_LANGS || {}, {
DE: {
  title: "VIRTUELLER SCHIESSSTAND",
  legTraj: "FLUGBAHN · NACH GESCHWINDIGKEIT", legLos: "VISIERLINIE", legBore: "LAUFACHSE", legGhost: "GEIST · VORHERIGER SCHUSS",
  modelBtn: "MODELLANNAHMEN", modelTitle: "MODELL",
  m: ["Punktmasse (3-DOF) — kein Gieren, kein aerodynamischer Sprung", "Widerstand: G1-Standardgeschoss Cd(Mach), skaliert mit 1/BC", "Luftdichte ρ(T, P, RH) · Schallgeschwindigkeit a(T)", "Integration: RK4 bei Δt = 2 ms", "Nullwinkel auf flacher Bahn gelöst, auf geneigten Schuss angewandt", "Drallabweichung: Litz-Näherung, SG nach Miller-Regel", "Coriolis: a = −2 Ω × v aus Breitengrad + Azimut", "Szene überhöht die Abweichung von der Visierlinie (Zielfernrohr 1:1)", "Kaliber nur Darstellung — der Widerstand steckt im BC"],
  mFoot: "TRAININGSVISUALISIERUNG — KEINE FEUERLEITLÖSUNG",
  atTarget: "AM ZIEL", dropL: "ABFALL", driftL: "ABDRIFT", velL: "GESCHWINDIGKEIT", energyL: "ENERGIE", tofL: "FLUGZEIT", zerosL: "NULLPUNKTE", apexRo: "SCHEITEL",
  targetFace: "SCHEIBE", ringsNote: "RINGE", noImpact: "KEIN TREFFER",
  tgtSizeL: "SCHEIBENTYP", scoreL: "WERTUNG", hitTxt: "TREFFER", missTxt: "FEHLSCHUSS", zoneTxt: function (z) { return "ZONE " + z; },
  tgtOpts: { ring50: "RINGSCHEIBE · Ø 50 cm", ring100: "RINGSCHEIBE · Ø 100 cm", gong30: "STAHLGONG · Ø 30 cm", ipsc: "IPSC-PAPIER · 45 × 57,5 cm", custom: "EIGENE PLATTE · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "ERSTELLT",
  fire: "FEUER", devScale: "BOGENÜBERHÖHUNG", skyLbl: "HIMMELSLICHT",
  paramsL: "PARAMETER", dispL: "ANZEIGE",
  viewMode: "ANSICHT", trueBtn: "REAL", arcBtn: "BOGEN", trueNote: "REALE GEOMETRIE · 1:1",
  uiTheme: "PANELS", sceneTheme: "SZENE", darkBtn: "DUNKEL", lightBtn: "HELL",
  cams: { side: "SEITE", top: "OBEN", shooter: "SCHÜTZE", scope: "OPTIK", free: "ORBIT", rifle: "GEWEHR" },
  ammo: "MUNITION", rifle: "GEWEHR & OPTIK", shotSec: "SCHUSS", envSec: "UMGEBUNG", advSec: "ERWEITERT", dopeSec: "DOPE-KARTE",
  custom: "Eigene", tgtLbl: "ZIEL", windLbl: "WIND", tgtRow: "ZIEL",
  mvL: "MÜNDUNGSGESCHWINDIGKEIT", massL: "GESCHOSSMASSE", bcL: "BALLIST. KOEFFIZIENT · G1", calL: "KALIBER", barrelL: "LAUFLÄNGE",
  scopeHL: "VISIERHÖHE ÜBER LAUF", zeroL: "EINSCHIESSENTFERNUNG", cantL: "VERKANTUNG · + = RECHTS", elevL: "HÖHENVERSTELLUNG", windAdjL: "SEITENVERSTELLUNG",
  railL: "SCHIENENNEIGUNG (BASIS)", mountL: "MONTAGENEIGUNG (RINGE)",
  tgtDistL: "ZIELENTFERNUNG", inclineL: "NEIGUNGSWINKEL",
  tempL: "TEMPERATUR", pressL: "LUFTDRUCK", humL: "LUFTFEUCHTE",
  spinLbl: "DRALLABWEICHUNG · RECHTSDRALL (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "BREITENGRAD", azL: "SCHUSSAZIMUT · 0=N",
  twistL: "DRALLLÄNGE", trainBtn: "TRAININGSMODUS", trainTitle: "TRAINING", roundL: "RUNDE", totalL: "GESAMT", ptsL: "PKT", nextBtn: "NÄCHSTE RUNDE ▸", exitBtn: "BEENDEN",
  trainHint: "Bedingungen zufällig gewählt — Wind, Entfernung und Temperatur ablesen, Türme einstellen, dann FEUER.",
  trainHit: function (p) { return "+" + p + " PKT"; },
  dRng: "ENT", dDrop: "FALL cm", dDrift: "DRIFT cm", dTof: "ZEIT",
  calm: "WINDSTILL", fromClock: function (h) { return "AUS " + h + " UHR"; }, driftsL: "DRIFT NACH LINKS", driftsR: "DRIFT NACH RECHTS", headTail: "GEGEN-/RÜCKENWIND",
  groundWarn: function (x) { return "⚠ GESCHOSS SCHLÄGT BEI " + x + " AUF — VOR DEM ZIEL"; },
  scaleNote: function (n) { return "ABWEICHUNG VON DER VISIERLINIE ×" + n; }, scopeNote: "ZIELFERNROHR · MASSSTAB 1:1",
  firingLine: "FEUERLINIE", wind: "WIND", near: "NAH-NULL", far: "FERN-NULL", apex: "SCHEITEL", transonic: "TRANSSONISCH", ground: "BODEN", impact: "EINSCHLAG", low: "TIEF", high: "HOCH", rr: "R", ll: "L",
  infoHint: "Mauszeiger über einen Parameter bewegen, um die Erklärung zu sehen.",
  info: {
    preset: ["PATRONEN-PRESET", "Werksladungen (Geschwindigkeit, Masse, BC, Kaliber). Jede Bewegung eines Munitionsreglers schaltet auf Eigene."],
    mv: ["MÜNDUNGSGESCHWINDIGKEIT", "Geschossgeschwindigkeit an der Mündung. Mehr Geschwindigkeit = flachere Bahn, kürzere Flugzeit, mehr Energie."],
    massGr: ["GESCHOSSMASSE", "Masse in Grain (1 gr = 64,8 mg). Bestimmt die Energie; das Widerstandsverhalten steckt im BC."],
    bc: ["BALLISTISCHER KOEFFIZIENT (G1)", "Wie gut das Geschoss dem Widerstand gegenüber dem G1-Standard widersteht. Höherer BC = flachere Bahn, weniger Windabdrift."],
    cal: ["KALIBER", "Geschossdurchmesser. Hier nur kosmetisch — der aerodynamische Effekt steckt im BC."],
    barrelLen: ["LAUFLÄNGE", "Längere Läufe verbrennen mehr Pulver vor dem Mündungsaustritt und erhöhen die Geschwindigkeit (~6,1 m/s pro Zoll, relativ zu 20\"). Lineare Näherung; ändert den BC nicht."],
    scopeH: ["VISIERHÖHE", "Vertikaler Abstand zwischen Laufachse und Zielfernrohrachse. Deshalb kreuzt das Geschoss die Visierlinie zweimal (Nah- und Fern-Null)."],
    zeroDist: ["EINSCHIESSENTFERNUNG", "Entfernung, in der sich Flugbahn und Visierlinie kreuzen. Definiert die Laufüberhöhung."],
    railMoa: ["SCHIENENNEIGUNG", "Feste Neigung der Basis (z. B. 20 MOA). Wird beim Einschießen kompensiert: der Treffpunkt bleibt im Haltepunkt; sie schafft nur zusätzlichen Höhenverstellweg für weite Entfernungen."],
    mountMoa: ["MONTAGENEIGUNG", "Zusätzliche Neigung aus verstellbaren Ringen, addiert zur Schiene."],
    cant: ["VERKANTUNG", "Gewehr um die Visierlinie gerollt. Kippt die eingebaute Überhöhung zur Seite: Schüsse gehen tief und in Richtung der Verkantung."],
    adjElev: ["HÖHENVERSTELLUNG", "Höhenturm des Zielfernrohrs (MOA/MIL). Positiv = Lauf zeigt höher = Treffpunkt steigt."],
    adjWind: ["SEITENVERSTELLUNG", "Seitenturm des Zielfernrohrs. Positiv = Treffpunkt wandert nach rechts."],
    targetDist: ["ZIELENTFERNUNG", "Entfernung zum Ziel entlang der Visierlinie."],
    incline: ["NEIGUNGSWINKEL", "Bergauf/bergab. Die Schwerkraft wirkt nur auf die Horizontalkomponente — geneigte Schüsse treffen hoch."],
    wind: ["WIND", "Geschwindigkeit und Uhrzeit-Richtung, AUS der der Wind weht (12 = vom Ziel). Seitenwind drückt das Geschoss; Gegen-/Rückenwind ändert wenig."],
    temp: ["TEMPERATUR", "Warme Luft ist dünner: weniger Widerstand, flacherer Schuss. Kalte Luft umgekehrt."],
    pressure: ["LUFTDRUCK", "Niedrigerer Stationsdruck (größere Höhe) = dünnere Luft = weniger Widerstand."],
    humidity: ["LUFTFEUCHTE", "Feuchte Luft ist geringfügig WENIGER dicht als trockene — sehr kleiner Effekt."],
    lat: ["BREITENGRAD", "Wo auf der Erde geschossen wird; skaliert die Coriolis-Ablenkung."],
    az: ["SCHUSSAZIMUT", "Kompassrichtung des Schusses (0 = Nord). Nach Osten hebt den Treffpunkt, nach Westen senkt ihn (Eötvös)."],
    spin: ["DRALLABWEICHUNG", "Gyroskopische Abdrift des rotierenden Geschosses — Rechtsdrall driftet nach rechts, wächst mit der Flugzeit."],
    twist: ["DRALLLÄNGE", "Zügesteigung — eine Umdrehung auf n Zoll. Schnellerer Drall (kleineres n): höhere Stabilität (SG, Miller-Regel), etwas mehr Drallabweichung. SG unter 1,0 = instabil."],
    cor: ["CORIOLIS + EÖTVÖS", "Erdrotationseffekte: horizontale Abdrift (Coriolis) und azimutabhängige Vertikalverschiebung (Eötvös)."],
    exag: ["ANSICHT", "REAL zeigt die echte Geometrie (1:1) — der Bogen ist auf Distanz fast unsichtbar. BOGEN überhöht die Abweichung von der Visierlinie. Alle Zahlen bleiben wahr; die Optik ist immer 1:1."],
    sky: ["HIMMELSLICHT", "Nur Szenenhelligkeit — kein ballistischer Effekt."],
    tgtSize: ["SCHEIBENTYP", "Physische Scheibe am Stand. Bestimmt Ringe/Zonen für die Wertung — nur Darstellung und Wertung, keine Ballistik."],
    theme: ["PANELS", "Hell/dunkel für die Bedienoberfläche. Die 3-D-Szene hat unten einen eigenen Schalter."],
    scene: ["SZENE", "Hell/dunkel für den 3-D-Stand — Himmel, Boden, Bahnmarker. Unabhängig von den Panels; HIMMELSLICHT feinjustiert weiter."],
  },
},
FR: {
  title: "STAND DE TIR VIRTUEL",
  legTraj: "TRAJECTOIRE · PAR VITESSE", legLos: "LIGNE DE VISÉE", legBore: "AXE DU CANON", legGhost: "FANTÔME · TIR PRÉCÉDENT",
  modelBtn: "HYPOTHÈSES DU MODÈLE", modelTitle: "MODÈLE",
  m: ["Masse ponctuelle (3-DOF) — pas de lacet ni de saut aérodynamique", "Traînée : Cd(Mach) du projectile étalon G1, mis à l'échelle par 1/BC", "Densité de l'air ρ(T, P, HR) · vitesse du son a(T)", "Intégration : RK4 à Δt = 2 ms", "Angle de zéro résolu sur pas de tir plat, appliqué au tir incliné", "Dérive gyroscopique : approximation de Litz, SG par la règle de Miller", "Coriolis : a = −2 Ω × v selon latitude + azimut", "La scène exagère l'écart à la ligne de visée (lunette à l'échelle 1:1)", "Le calibre n'affecte que l'affichage — la traînée est portée par le BC"],
  mFoot: "VISUALISATION D'ENTRAÎNEMENT — PAS UNE SOLUTION DE TIR",
  atTarget: "SUR CIBLE", dropL: "CHUTE", driftL: "DÉRIVE", velL: "VITESSE", energyL: "ÉNERGIE", tofL: "TEMPS DE VOL", zerosL: "ZÉROS", apexRo: "APEX",
  targetFace: "CIBLE", ringsNote: "ANNEAUX", noImpact: "AUCUN IMPACT",
  tgtSizeL: "TYPE DE CIBLE", scoreL: "SCORE", hitTxt: "TOUCHÉ", missTxt: "MANQUÉ", zoneTxt: function (z) { return "ZONE " + z; },
  tgtOpts: { ring50: "CIBLE À ANNEAUX · Ø 50 cm", ring100: "CIBLE À ANNEAUX · Ø 100 cm", gong30: "GONG ACIER · Ø 30 cm", ipsc: "PAPIER IPSC · 45 × 57,5 cm", custom: "PLAQUE PERSO · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GÉNÉRÉ",
  fire: "FEU", devScale: "GROSSISSEMENT DE L'ARC", skyLbl: "LUMIÈRE DU CIEL",
  paramsL: "PARAMÈTRES", dispL: "AFFICHAGE",
  viewMode: "MODE DE VUE", trueBtn: "RÉEL", arcBtn: "ARC", trueNote: "GÉOMÉTRIE RÉELLE · 1:1",
  uiTheme: "PANNEAUX", sceneTheme: "SCÈNE", darkBtn: "SOMBRE", lightBtn: "CLAIR",
  cams: { side: "CÔTÉ", top: "DESSUS", shooter: "TIREUR", scope: "LUNETTE", free: "ORBITE", rifle: "CARABINE" },
  ammo: "MUNITION", rifle: "CARABINE & OPTIQUE", shotSec: "TIR", envSec: "ENVIRONNEMENT", advSec: "AVANCÉ", dopeSec: "TABLE DOPE",
  custom: "Perso", tgtLbl: "CIBLE", windLbl: "VENT", tgtRow: "CIBLE",
  mvL: "VITESSE INITIALE", massL: "MASSE DU PROJECTILE", bcL: "COEFF. BALISTIQUE · G1", calL: "CALIBRE", barrelL: "LONGUEUR DU CANON",
  scopeHL: "HAUTEUR DE LUNETTE", zeroL: "DISTANCE DE ZÉRO", cantL: "DÉVERS · + = DROITE", elevL: "CORRECTION VERTICALE", windAdjL: "CORRECTION LATÉRALE",
  railL: "PENTE DU RAIL (EMBASE)", mountL: "PENTE DU MONTAGE (COLLIERS)",
  tgtDistL: "DISTANCE DE LA CIBLE", inclineL: "ANGLE DE SITE",
  tempL: "TEMPÉRATURE", pressL: "PRESSION", humL: "HUMIDITÉ",
  spinLbl: "DÉRIVE GYRO. · PAS À DROITE (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "LATITUDE", azL: "AZIMUT DU TIR · 0=N",
  twistL: "PAS DE RAYURE", trainBtn: "MODE ENTRAÎNEMENT", trainTitle: "ENTRAÎNEMENT", roundL: "MANCHE", totalL: "TOTAL", ptsL: "PTS", nextBtn: "MANCHE SUIVANTE ▸", exitBtn: "QUITTER",
  trainHint: "Conditions aléatoires — lisez le vent, la distance et la température, réglez vos tourelles, puis FEU.",
  trainHit: function (p) { return "+" + p + " PTS"; },
  dRng: "DST", dDrop: "CHUTE cm", dDrift: "DÉR cm", dTof: "TDV",
  calm: "CALME", fromClock: function (h) { return "DE " + h + " HEURES"; }, driftsL: "DÉRIVE À GAUCHE", driftsR: "DÉRIVE À DROITE", headTail: "FACE/DOS",
  groundWarn: function (x) { return "⚠ LE PROJECTILE TOUCHE LE SOL À " + x + " — AVANT LA CIBLE"; },
  scaleNote: function (n) { return "ÉCART À LA LIGNE DE VISÉE ×" + n; }, scopeNote: "VUE LUNETTE · ÉCHELLE 1:1",
  firingLine: "PAS DE TIR", wind: "VENT", near: "ZÉRO PROCHE", far: "ZÉRO LOIN", apex: "APEX", transonic: "TRANSSONIQUE", ground: "SOL", impact: "IMPACT", low: "BAS", high: "HAUT", rr: "D", ll: "G",
  infoHint: "Survolez un paramètre pour voir son explication.",
  info: {
    preset: ["PRESET DE CARTOUCHE", "Chargements d'usine (vitesse, masse, BC, calibre). Bouger un curseur de munition passe en Perso."],
    mv: ["VITESSE INITIALE", "Vitesse du projectile à la bouche. Plus de vitesse = arc plus tendu, vol plus court, plus d'énergie."],
    massGr: ["MASSE DU PROJECTILE", "Masse en grains (1 gr = 64,8 mg). Fixe l'énergie cinétique ; le comportement en traînée vient du BC."],
    bc: ["COEFFICIENT BALISTIQUE (G1)", "Capacité du projectile à vaincre la traînée face à l'étalon G1. BC plus élevé = trajectoire plus tendue, moins de dérive au vent."],
    cal: ["CALIBRE", "Diamètre du projectile. Cosmétique ici — l'effet aérodynamique est déjà dans le BC."],
    barrelLen: ["LONGUEUR DU CANON", "Un canon plus long brûle plus de poudre avant la sortie, augmentant la vitesse initiale (~6,1 m/s par pouce, réf. 20\"). Approximation linéaire ; ne change pas le BC."],
    scopeH: ["HAUTEUR DE LUNETTE", "Décalage vertical entre l'axe du canon et celui de la lunette. C'est pourquoi la balle croise la ligne de visée deux fois (zéro proche et loin)."],
    zeroDist: ["DISTANCE DE ZÉRO", "Distance où trajectoire et ligne de visée se croisent. Définit l'inclinaison du canon."],
    railMoa: ["PENTE DU RAIL", "Pente fixe usinée dans l'embase (ex. 20 MOA). Compensée au zérotage : l'impact reste au point visé ; elle libère seulement de la course en hausse pour le tir lointain."],
    mountMoa: ["PENTE DU MONTAGE", "Pente supplémentaire des colliers réglables, ajoutée au rail."],
    cant: ["DÉVERS", "Carabine roulée autour de la ligne de visée. Bascule la hausse intégrée : les tirs partent bas et du côté du dévers."],
    adjElev: ["CORRECTION VERTICALE", "Tourelle d'élévation (MOA/MIL). Positif = canon plus haut = impact qui monte."],
    adjWind: ["CORRECTION LATÉRALE", "Tourelle de dérive. Positif = impact vers la droite."],
    targetDist: ["DISTANCE DE LA CIBLE", "Distance à la cible mesurée le long de la ligne de visée."],
    incline: ["ANGLE DE SITE", "Tir en montée/descente. La gravité n'agit que sur la composante horizontale : les tirs inclinés touchent haut."],
    wind: ["VENT", "Vitesse et direction horaire D'OÙ vient le vent (12 = de la cible). Le vent de travers dévie la balle ; face/dos change peu."],
    temp: ["TEMPÉRATURE", "L'air chaud est plus léger : moins de traînée, tir plus tendu. L'air froid fait l'inverse."],
    pressure: ["PRESSION", "Pression station plus basse (altitude) = air plus léger = moins de traînée."],
    humidity: ["HUMIDITÉ", "L'air humide est légèrement MOINS dense que l'air sec — effet très faible."],
    lat: ["LATITUDE", "Où vous tirez sur Terre ; module la déviation de Coriolis."],
    az: ["AZIMUT DU TIR", "Cap boussole du tir (0 = nord). Tirer vers l'est relève l'impact, vers l'ouest l'abaisse (Eötvös)."],
    spin: ["DÉRIVE GYROSCOPIQUE", "Dérive du projectile en rotation — pas à droite dérive à droite, croît avec le temps de vol."],
    twist: ["PAS DE RAYURE", "Un tour en n pouces. Pas plus rapide (n plus petit) : meilleure stabilité (SG, règle de Miller) mais un peu plus de dérive. SG sous 1,0 = projectile instable."],
    cor: ["CORIOLIS + EÖTVÖS", "Effets de rotation terrestre : dérive horizontale (Coriolis) et décalage vertical selon l'azimut (Eötvös)."],
    exag: ["MODE DE VUE", "RÉEL montre la géométrie 1:1 — l'arc est presque invisible à distance. ARC grossit l'écart à la ligne de visée. Les chiffres restent vrais ; la lunette est toujours 1:1."],
    sky: ["LUMIÈRE DU CIEL", "Luminosité de la scène uniquement — aucun effet balistique."],
    tgtSize: ["TYPE DE CIBLE", "Cible physique au stand. Définit anneaux/zones pour le score — affichage et score seulement, pas de balistique."],
    theme: ["PANNEAUX", "Clair/sombre pour l'interface. La scène 3D a son propre réglage plus bas."],
    scene: ["SCÈNE", "Clair/sombre pour le stand 3D — ciel, sol, marqueurs. Indépendant des panneaux ; LUMIÈRE DU CIEL affine encore."],
  },
},
ES: {
  title: "CAMPO DE TIRO VIRTUAL",
  legTraj: "TRAYECTORIA · POR VELOCIDAD", legLos: "LÍNEA DE MIRA", legBore: "EJE DEL CAÑÓN", legGhost: "FANTASMA · DISPARO ANTERIOR",
  modelBtn: "SUPUESTOS DEL MODELO", modelTitle: "MODELO",
  m: ["Masa puntual (3-DOF) — sin guiñada ni salto aerodinámico", "Resistencia: Cd(Mach) del proyectil patrón G1, escalado por 1/BC", "Densidad del aire ρ(T, P, HR) · velocidad del sonido a(T)", "Integración: RK4 con Δt = 2 ms", "Ángulo de cero resuelto en campo llano, aplicado al tiro inclinado", "Deriva giroscópica: aproximación de Litz, SG por la regla de Miller", "Coriolis: a = −2 Ω × v según latitud + acimut", "La escena exagera la desviación de la línea de mira (visor a escala 1:1)", "El calibre solo afecta la imagen — la resistencia la lleva el BC"],
  mFoot: "VISUALIZACIÓN DE ENTRENAMIENTO — NO ES UNA SOLUCIÓN DE TIRO",
  atTarget: "EN EL BLANCO", dropL: "CAÍDA", driftL: "DERIVA", velL: "VELOCIDAD", energyL: "ENERGÍA", tofL: "TIEMPO DE VUELO", zerosL: "CEROS", apexRo: "ÁPICE",
  targetFace: "BLANCO", ringsNote: "ANILLOS", noImpact: "SIN IMPACTO",
  tgtSizeL: "TIPO DE BLANCO", scoreL: "PUNTUACIÓN", hitTxt: "IMPACTO", missTxt: "FALLO", zoneTxt: function (z) { return "ZONA " + z; },
  tgtOpts: { ring50: "BLANCO DE ANILLOS · Ø 50 cm", ring100: "BLANCO DE ANILLOS · Ø 100 cm", gong30: "GONG DE ACERO · Ø 30 cm", ipsc: "PAPEL IPSC · 45 × 57,5 cm", custom: "PLACA PERSONAL · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GENERADO",
  fire: "FUEGO", devScale: "AUMENTO DEL ARCO", skyLbl: "LUZ DEL CIELO",
  paramsL: "PARÁMETROS", dispL: "PANTALLA",
  viewMode: "MODO DE VISTA", trueBtn: "REAL", arcBtn: "ARCO", trueNote: "GEOMETRÍA REAL · 1:1",
  uiTheme: "PANELES", sceneTheme: "ESCENA", darkBtn: "OSCURO", lightBtn: "CLARO",
  cams: { side: "LADO", top: "ARRIBA", shooter: "TIRADOR", scope: "VISOR", free: "ÓRBITA", rifle: "RIFLE" },
  ammo: "MUNICIÓN", rifle: "RIFLE Y ÓPTICA", shotSec: "DISPARO", envSec: "ENTORNO", advSec: "AVANZADO", dopeSec: "TABLA DOPE",
  custom: "Personal", tgtLbl: "BLANCO", windLbl: "VIENTO", tgtRow: "BLANCO",
  mvL: "VELOCIDAD INICIAL", massL: "MASA DE LA BALA", bcL: "COEF. BALÍSTICO · G1", calL: "CALIBRE", barrelL: "LONGITUD DEL CAÑÓN",
  scopeHL: "ALTURA DEL VISOR", zeroL: "DISTANCIA DE CERO", cantL: "INCLINACIÓN · + = DERECHA", elevL: "AJUSTE VERTICAL", windAdjL: "AJUSTE LATERAL",
  railL: "PENDIENTE DEL RAÍL (BASE)", mountL: "PENDIENTE DE MONTURAS",
  tgtDistL: "DISTANCIA AL BLANCO", inclineL: "ÁNGULO DE INCLINACIÓN",
  tempL: "TEMPERATURA", pressL: "PRESIÓN", humL: "HUMEDAD",
  spinLbl: "DERIVA GIRO. · ESTRÍA DERECHA (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "LATITUD", azL: "ACIMUT DEL TIRO · 0=N",
  twistL: "PASO DE ESTRÍA", trainBtn: "MODO ENTRENAMIENTO", trainTitle: "ENTRENAMIENTO", roundL: "RONDA", totalL: "TOTAL", ptsL: "PTS", nextBtn: "SIGUIENTE RONDA ▸", exitBtn: "SALIR",
  trainHint: "Condiciones aleatorias: lee el viento, la distancia y la temperatura, ajusta las torretas y dispara.",
  trainHit: function (p) { return "+" + p + " PTS"; },
  dRng: "DST", dDrop: "CAÍDA cm", dDrift: "DER cm", dTof: "TDV",
  calm: "EN CALMA", fromClock: function (h) { return "DESDE LAS " + h; }, driftsL: "DERIVA A IZQUIERDA", driftsR: "DERIVA A DERECHA", headTail: "DE FRENTE/COLA",
  groundWarn: function (x) { return "⚠ LA BALA GOLPEA EL SUELO A " + x + " — ANTES DEL BLANCO"; },
  scaleNote: function (n) { return "DESVIACIÓN DE LA LÍNEA DE MIRA ×" + n; }, scopeNote: "VISTA DE VISOR · ESCALA 1:1",
  firingLine: "LÍNEA DE FUEGO", wind: "VIENTO", near: "CERO CERCANO", far: "CERO LEJANO", apex: "ÁPICE", transonic: "TRANSÓNICO", ground: "SUELO", impact: "IMPACTO", low: "BAJO", high: "ALTO", rr: "D", ll: "I",
  infoHint: "Pasa el cursor sobre un parámetro para ver su explicación.",
  info: {
    preset: ["CARTUCHO (PRESET)", "Cargas de fábrica (velocidad, masa, BC, calibre). Mover cualquier control de munición cambia a Personal."],
    mv: ["VELOCIDAD INICIAL", "Velocidad de la bala en la boca. Más velocidad = arco más plano, menos tiempo de vuelo, más energía."],
    massGr: ["MASA DE LA BALA", "Masa en granos (1 gr = 64,8 mg). Fija la energía cinética; el comportamiento de resistencia viene del BC."],
    bc: ["COEFICIENTE BALÍSTICO (G1)", "Capacidad de la bala frente a la resistencia respecto al patrón G1. Mayor BC = trayectoria más plana y menos deriva por viento."],
    cal: ["CALIBRE", "Diámetro de la bala. Aquí es cosmético — el efecto aerodinámico ya está en el BC."],
    barrelLen: ["LONGITUD DEL CAÑÓN", "Un cañón más largo quema más pólvora antes de la salida, subiendo la velocidad (~6,1 m/s por pulgada, ref. 20\"). Aproximación lineal; no cambia el BC."],
    scopeH: ["ALTURA DEL VISOR", "Separación vertical entre el eje del cañón y el del visor. Por eso la bala cruza la línea de mira dos veces (cero cercano y lejano)."],
    zeroDist: ["DISTANCIA DE CERO", "Distancia donde trayectoria y línea de mira se cruzan. Define la elevación del cañón."],
    railMoa: ["PENDIENTE DEL RAÍL", "Inclinación fija de la base (p. ej. 20 MOA). Se compensa al poner a cero: el impacto queda en el punto de mira; solo libera recorrido extra de elevación para larga distancia."],
    mountMoa: ["PENDIENTE DE MONTURAS", "Inclinación adicional de las monturas regulables, sumada al raíl."],
    cant: ["INCLINACIÓN LATERAL", "Rifle girado sobre la línea de mira. Ladea la elevación integrada: los tiros van bajos y hacia el lado inclinado."],
    adjElev: ["AJUSTE VERTICAL", "Torreta de elevación (MOA/MIL). Positivo = cañón más alto = impacto más arriba."],
    adjWind: ["AJUSTE LATERAL", "Torreta de deriva. Positivo = impacto hacia la derecha."],
    targetDist: ["DISTANCIA AL BLANCO", "Distancia al blanco medida a lo largo de la línea de mira."],
    incline: ["ÁNGULO DE INCLINACIÓN", "Tiro cuesta arriba/abajo. La gravedad actúa solo sobre la componente horizontal: los tiros inclinados pegan alto."],
    wind: ["VIENTO", "Velocidad y dirección horaria DESDE donde sopla (12 = desde el blanco). El viento cruzado desvía la bala; frente/cola cambia poco."],
    temp: ["TEMPERATURA", "El aire cálido es menos denso: menos resistencia, tiro más plano. El frío, lo contrario."],
    pressure: ["PRESIÓN", "Menos presión de estación (más altitud) = aire menos denso = menos resistencia."],
    humidity: ["HUMEDAD", "El aire húmedo es ligeramente MENOS denso que el seco — efecto muy pequeño."],
    lat: ["LATITUD", "Dónde disparas en la Tierra; escala la desviación de Coriolis."],
    az: ["ACIMUT DEL TIRO", "Rumbo de brújula del disparo (0 = norte). Hacia el este sube el impacto, hacia el oeste lo baja (Eötvös)."],
    spin: ["DERIVA GIROSCÓPICA", "Deriva de la bala en rotación — estría derecha deriva a la derecha, crece con el tiempo de vuelo."],
    twist: ["PASO DE ESTRÍA", "Una vuelta en n pulgadas. Paso más rápido (n menor): más estabilidad (SG, regla de Miller) pero algo más de deriva. SG bajo 1,0 = bala inestable."],
    cor: ["CORIOLIS + EÖTVÖS", "Efectos de la rotación terrestre: deriva horizontal (Coriolis) y desplazamiento vertical según el acimut (Eötvös)."],
    exag: ["MODO DE VISTA", "REAL muestra la geometría 1:1 — el arco casi no se ve a distancia. ARCO amplifica la desviación de la línea de mira. Los números siguen siendo reales; el visor siempre es 1:1."],
    sky: ["LUZ DEL CIELO", "Solo brillo de la escena — sin efecto balístico."],
    tgtSize: ["TIPO DE BLANCO", "Blanco físico en el puesto. Define anillos/zonas para puntuar — solo imagen y puntuación, sin balística."],
    theme: ["PANELES", "Claro/oscuro para la interfaz. La escena 3D tiene su propio conmutador abajo."],
    scene: ["ESCENA", "Claro/oscuro para el campo 3D — cielo, suelo, marcadores. Independiente de los paneles; LUZ DEL CIELO sigue ajustando."],
  },
},
});
