window.VSR_LANGS = Object.assign(window.VSR_LANGS || {}, {
SV: {
  title: "VIRTUELL SKJUTBANA",
  legTraj: "KULBANA · EFTER HASTIGHET", legLos: "SIKTLINJE", legBore: "PIPANS AXEL", legGhost: "SPÖKE · FÖREGÅENDE SKOTT",
  modelBtn: "MODELLANTAGANDEN", modelTitle: "MODELL",
  m: ["Punktmassa (3-DOF) — ingen gir, inget aerodynamiskt hopp", "Luftmotstånd: G1-standardprojektil Cd(Mach), skalad med 1/BC", "Luftdensitet ρ(T, P, RF) · ljudhastighet a(T)", "Integration: RK4 med Δt = 2 ms", "Nollvinkel löst på plan bana, tillämpad på lutande skott", "Spinndrift: Litz-approximation, SG enligt Millers regel", "Coriolis: a = −2 Ω × v från latitud + azimut", "Scenen överdriver avvikelsen från siktlinjen (kikarsiktet är 1:1)", "Kalibern påverkar bara bilden — motståndet ligger i BC"],
  mFoot: "TRÄNINGSVISUALISERING — INGEN ELDLÖSNING",
  atTarget: "VID MÅLET", dropL: "FALL", driftL: "AVDRIFT", velL: "HASTIGHET", energyL: "ENERGI", tofL: "FLYGTID", zerosL: "NOLLPUNKTER", apexRo: "KULMEN",
  targetFace: "TAVLA", ringsNote: "RINGAR", noImpact: "INGEN TRÄFF",
  tgtSizeL: "MÅLTYP", scoreL: "POÄNG", hitTxt: "TRÄFF", missTxt: "BOM", zoneTxt: function (z) { return "ZON " + z; },
  tgtOpts: { ring50: "RINGTAVLA · Ø 50 cm", ring100: "RINGTAVLA · Ø 100 cm", gong30: "STÅLGONG · Ø 30 cm", ipsc: "IPSC-PAPPER · 45 × 57,5 cm", custom: "EGEN PLÅT · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GENERERAD",
  fire: "ELD", devScale: "BÅGFÖRSTORING", skyLbl: "HIMMELSLJUS",
  paramsL: "PARAMETRAR", dispL: "VISNING",
  viewMode: "VYLÄGE", trueBtn: "VERKLIG", arcBtn: "BÅGE", trueNote: "VERKLIG GEOMETRI · 1:1",
  uiTheme: "PANELER", sceneTheme: "SCEN", darkBtn: "MÖRK", lightBtn: "LJUS",
  cams: { side: "SIDA", top: "OVAN", shooter: "SKYTT", scope: "KIKARE", free: "OMLOPP", rifle: "GEVÄR" },
  ammo: "AMMUNITION", rifle: "GEVÄR & OPTIK", shotSec: "SKOTT", envSec: "MILJÖ", advSec: "AVANCERAT", dopeSec: "DOPE-KORT",
  custom: "Egen", tgtLbl: "MÅL", windLbl: "VIND", tgtRow: "MÅL",
  mvL: "MYNNINGSHASTIGHET", massL: "KULVIKT", bcL: "BALLISTISK KOEFF. · G1", calL: "KALIBER", barrelL: "PIPLÄNGD",
  scopeHL: "SIKTESHÖJD ÖVER PIPAN", zeroL: "INSKJUTNINGSAVSTÅND", cantL: "LUTNING · + = HÖGER", elevL: "HÖJDJUSTERING", windAdjL: "SIDJUSTERING",
  railL: "SKENLUTNING (BAS)", mountL: "FÄSTLUTNING (RINGAR)",
  tgtDistL: "MÅLAVSTÅND", inclineL: "LUTNINGSVINKEL",
  tempL: "TEMPERATUR", pressL: "LUFTTRYCK", humL: "LUFTFUKTIGHET",
  spinLbl: "SPINNDRIFT · HÖGERRÄFFLING (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "LATITUD", azL: "SKOTTAZIMUT · 0=N",
  twistL: "RÄFFELSTIGNING", trainBtn: "TRÄNINGSLÄGE", trainTitle: "TRÄNING", roundL: "OMGÅNG", totalL: "TOTALT", ptsL: "P", nextBtn: "NÄSTA OMGÅNG ▸", exitBtn: "AVSLUTA",
  trainHint: "Slumpade förhållanden — läs vind, avstånd och temperatur, ställ tornen, sedan ELD.",
  trainHit: function (p) { return "+" + p + " P"; },
  dRng: "AVS", dDrop: "FALL cm", dDrift: "DRF cm", dTof: "TID",
  calm: "VINDSTILLA", fromClock: function (h) { return "FRÅN KL " + h; }, driftsL: "DRIVER VÄNSTER", driftsR: "DRIVER HÖGER", headTail: "MOT-/MEDVIND",
  groundWarn: function (x) { return "⚠ KULAN SLÅR I MARKEN VID " + x + " — FÖRE MÅLET"; },
  scaleNote: function (n) { return "AVVIKELSE FRÅN SIKTLINJEN ×" + n; }, scopeNote: "KIKARVY · SKALA 1:1",
  firingLine: "ELDLINJE", wind: "VIND", near: "NÄRA NOLLA", far: "BORTRE NOLLA", apex: "KULMEN", transonic: "TRANSSONISK", ground: "MARK", impact: "NEDSLAG", low: "LÅGT", high: "HÖGT", rr: "H", ll: "V",
  infoHint: "Hovra över en parameter för att se förklaringen.",
  info: {
    preset: ["PATRON-FÖRVAL", "Fabriksladdningar (hastighet, vikt, BC, kaliber). Rör du någon ammunitionsreglage växlar det till Egen."],
    mv: ["MYNNINGSHASTIGHET", "Kulans fart vid mynningen. Högre fart = flackare bana, kortare flygtid, mer energi."],
    massGr: ["KULVIKT", "Vikt i grain (1 gr = 64,8 mg). Bestämmer energin; motståndsbeteendet ligger i BC."],
    bc: ["BALLISTISK KOEFFICIENT (G1)", "Hur väl kulan trotsar luftmotståndet jämfört med G1-standarden. Högre BC = flackare bana och mindre vindavdrift."],
    cal: ["KALIBER", "Kulans diameter. Endast kosmetisk här — den aerodynamiska effekten ligger i BC."],
    barrelLen: ["PIPLÄNGD", "Längre pipa bränner mer krut före mynningen och höjer hastigheten (~6,1 m/s per tum, ref. 20\"). Linjär approximation; ändrar inte BC."],
    scopeH: ["SIKTESHÖJD", "Vertikalt avstånd mellan pipans axel och siktets axel. Därför korsar kulan siktlinjen två gånger (nära och bortre nolla)."],
    zeroDist: ["INSKJUTNINGSAVSTÅND", "Avstånd där kulbanan och siktlinjen korsas. Definierar pipans uppåtvinkel."],
    railMoa: ["SKENLUTNING", "Fast lutning i basen (t.ex. 20 MOA). Kompenseras inte här: lyfter träffen tills du vrider ned höjden."],
    mountMoa: ["FÄSTLUTNING", "Extra lutning från justerbara ringar, adderad till skenan."],
    cant: ["LUTNING", "Geväret rullat kring siktlinjen. Tippar den inbyggda höjden åt sidan: skotten går lågt och åt lutningshållet."],
    adjElev: ["HÖJDJUSTERING", "Siktets höjdtorn (MOA/MIL). Positivt = pipan pekar högre = träffen stiger."],
    adjWind: ["SIDJUSTERING", "Siktets sidotorn. Positivt = träffen flyttas åt höger."],
    targetDist: ["MÅLAVSTÅND", "Avstånd till målet mätt längs siktlinjen."],
    incline: ["LUTNINGSVINKEL", "Upp-/nedförsbacke. Gravitationen verkar bara på den horisontella komponenten: lutande skott träffar högt."],
    wind: ["VIND", "Hastighet och klockriktning som vinden blåser FRÅN (12 = från målet). Sidvind driver kulan; mot-/medvind ändrar lite."],
    temp: ["TEMPERATUR", "Varm luft är tunnare: mindre motstånd, flackare skott. Kall luft gör tvärtom."],
    pressure: ["LUFTTRYCK", "Lägre stationstryck (högre höjd) = tunnare luft = mindre motstånd."],
    humidity: ["LUFTFUKTIGHET", "Fuktig luft är något MINDRE tät än torr — en mycket liten effekt."],
    lat: ["LATITUD", "Var på jorden du skjuter; skalar Coriolis-avböjningen."],
    az: ["SKOTTAZIMUT", "Kompassriktning för skottet (0 = norr). Österut lyfter träffen, västerut sänker den (Eötvös)."],
    spin: ["SPINNDRIFT", "Gyroskopisk drift från den roterande kulan — högerräffling driver åt höger, växer med flygtiden."],
    twist: ["RÄFFELSTIGNING", "Ett varv på n tum. Snabbare stigning (mindre n): högre stabilitet (SG, Millers regel) men lite mer spinndrift. SG under 1,0 = instabil kula."],
    cor: ["CORIOLIS + EÖTVÖS", "Jordrotationseffekter: horisontell drift (Coriolis) och vertikal förskjutning beroende på azimut (Eötvös)."],
    exag: ["VYLÄGE", "VERKLIG visar den sanna geometrin (1:1) — bågen är nästan osynlig på avstånd. BÅGE förstorar avvikelsen från siktlinjen. Alla siffror förblir sanna; kikaren är alltid 1:1."],
    sky: ["HIMMELSLJUS", "Endast scenens ljusstyrka — ingen ballistisk effekt."],
    tgtSize: ["MÅLTYP", "Fysiskt mål på banan. Bestämmer ringar/zoner för poängen — endast bild och poäng, ingen ballistik."],
    theme: ["PANELER", "Ljust/mörkt för gränssnittet. 3D-scenen har en egen omkopplare nedan."],
    scene: ["SCEN", "Ljust/mörkt för 3D-banan — himmel, mark, markörer. Oberoende av panelerna; HIMMELSLJUS finjusterar ändå."],
  },
},
DA: {
  title: "VIRTUEL SKYDEBANE",
  legTraj: "KUGLEBANE · EFTER HASTIGHED", legLos: "SIGTELINJE", legBore: "LØBETS AKSE", legGhost: "SPØGELSE · FORRIGE SKUD",
  modelBtn: "MODELANTAGELSER", modelTitle: "MODEL",
  m: ["Punktmasse (3-DOF) — ingen giring, intet aerodynamisk spring", "Luftmodstand: G1-standardprojektil Cd(Mach), skaleret med 1/BC", "Luftdensitet ρ(T, P, RF) · lydens hastighed a(T)", "Integration: RK4 med Δt = 2 ms", "Nulvinkel løst på flad bane, anvendt på skråt skud", "Spindrift: Litz-tilnærmelse, SG efter Millers regel", "Coriolis: a = −2 Ω × v fra breddegrad + azimut", "Scenen overdriver afvigelsen fra sigtelinjen (kikkerten er 1:1)", "Kaliberet påvirker kun visningen — modstanden ligger i BC"],
  mFoot: "TRÆNINGSVISUALISERING — IKKE EN SKYDELØSNING",
  atTarget: "VED MÅLET", dropL: "FALD", driftL: "AFDRIFT", velL: "HASTIGHED", energyL: "ENERGI", tofL: "FLYVETID", zerosL: "NULPUNKTER", apexRo: "TOPPUNKT",
  targetFace: "SKIVE", ringsNote: "RINGE", noImpact: "INGEN TRÆFFER",
  tgtSizeL: "MÅLTYPE", scoreL: "POINT", hitTxt: "TRÆFFER", missTxt: "FORBIER", zoneTxt: function (z) { return "ZONE " + z; },
  tgtOpts: { ring50: "RINGSKIVE · Ø 50 cm", ring100: "RINGSKIVE · Ø 100 cm", gong30: "STÅLGONG · Ø 30 cm", ipsc: "IPSC-PAPIR · 45 × 57,5 cm", custom: "EGEN PLADE · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GENERERET",
  fire: "FYR", devScale: "BUEFORSTØRRELSE", skyLbl: "HIMMELLYS",
  paramsL: "PARAMETRE", dispL: "VISNING",
  viewMode: "VISNINGSTILSTAND", trueBtn: "REEL", arcBtn: "BUE", trueNote: "REEL GEOMETRI · 1:1",
  uiTheme: "PANELER", sceneTheme: "SCENE", darkBtn: "MØRK", lightBtn: "LYS",
  cams: { side: "SIDE", top: "TOP", shooter: "SKYTTE", scope: "KIKKERT", free: "KREDSLØB", rifle: "RIFFEL" },
  ammo: "AMMUNITION", rifle: "RIFFEL & OPTIK", shotSec: "SKUD", envSec: "MILJØ", advSec: "AVANCERET", dopeSec: "DOPE-KORT",
  custom: "Egen", tgtLbl: "MÅL", windLbl: "VIND", tgtRow: "MÅL",
  mvL: "MUNDINGSHASTIGHED", massL: "KUGLEVÆGT", bcL: "BALLISTISK KOEFF. · G1", calL: "KALIBER", barrelL: "LØBSLÆNGDE",
  scopeHL: "SIGTEHØJDE OVER LØBET", zeroL: "INDSKYDNINGSAFSTAND", cantL: "HÆLDNING · + = HØJRE", elevL: "HØJDEJUSTERING", windAdjL: "SIDEJUSTERING",
  railL: "SKINNEHÆLDNING (BASE)", mountL: "MONTAGEHÆLDNING (RINGE)",
  tgtDistL: "MÅLAFSTAND", inclineL: "HÆLDNINGSVINKEL",
  tempL: "TEMPERATUR", pressL: "LUFTTRYK", humL: "LUFTFUGTIGHED",
  spinLbl: "SPINDRIFT · HØJRERIFLING (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "BREDDEGRAD", azL: "SKUDAZIMUT · 0=N",
  twistL: "RIFFELSTIGNING", trainBtn: "TRÆNINGSTILSTAND", trainTitle: "TRÆNING", roundL: "RUNDE", totalL: "I ALT", ptsL: "P", nextBtn: "NÆSTE RUNDE ▸", exitBtn: "AFSLUT",
  trainHint: "Tilfældige forhold — aflæs vind, afstand og temperatur, indstil tårnene, og FYR.",
  trainHit: function (p) { return "+" + p + " P"; },
  dRng: "AFS", dDrop: "FALD cm", dDrift: "DRF cm", dTof: "TID",
  calm: "VINDSTILLE", fromClock: function (h) { return "FRA KL. " + h; }, driftsL: "DRIVER VENSTRE", driftsR: "DRIVER HØJRE", headTail: "MOD-/MEDVIND",
  groundWarn: function (x) { return "⚠ KUGLEN RAMMER JORDEN VED " + x + " — FØR MÅLET"; },
  scaleNote: function (n) { return "AFVIGELSE FRA SIGTELINJEN ×" + n; }, scopeNote: "KIKKERTVISNING · SKALA 1:1",
  firingLine: "SKYDELINJE", wind: "VIND", near: "NÆRT NUL", far: "FJERNT NUL", apex: "TOP", transonic: "TRANSSONISK", ground: "JORD", impact: "NEDSLAG", low: "LAVT", high: "HØJT", rr: "H", ll: "V",
  infoHint: "Hold musen over en parameter for at se forklaringen.",
  info: {
    preset: ["PATRON-FORVALG", "Fabriksladninger (hastighed, vægt, BC, kaliber). Flyttes en ammunitionsskyder, skiftes til Egen."],
    mv: ["MUNDINGSHASTIGHED", "Kuglens fart ved mundingen. Mere fart = fladere bane, kortere flyvetid, mere energi."],
    massGr: ["KUGLEVÆGT", "Vægt i grain (1 gr = 64,8 mg). Bestemmer energien; modstandsadfærden ligger i BC."],
    bc: ["BALLISTISK KOEFFICIENT (G1)", "Hvor godt kuglen bekæmper modstanden i forhold til G1-standarden. Højere BC = fladere bane og mindre vindafdrift."],
    cal: ["KALIBER", "Kuglens diameter. Kun kosmetisk her — den aerodynamiske effekt ligger i BC."],
    barrelLen: ["LØBSLÆNGDE", "Et længere løb brænder mere krudt før mundingen og øger hastigheden (~6,1 m/s pr. tomme, ref. 20\"). Lineær tilnærmelse; ændrer ikke BC."],
    scopeH: ["SIGTEHØJDE", "Lodret afstand mellem løbets akse og kikkertens akse. Derfor krydser kuglen sigtelinjen to gange (nært og fjernt nul)."],
    zeroDist: ["INDSKYDNINGSAFSTAND", "Afstand hvor kuglebane og sigtelinje krydser. Definerer løbets opadvinkel."],
    railMoa: ["SKINNEHÆLDNING", "Fast hældning i basen (fx 20 MOA). Kompenseres ikke her: løfter træfpunktet, indtil du drejer højden ned."],
    mountMoa: ["MONTAGEHÆLDNING", "Ekstra hældning fra justerbare ringe, lagt til skinnen."],
    cant: ["HÆLDNING", "Riflen rullet om sigtelinjen. Vipper den indbyggede elevation til siden: skud går lavt og mod hældningen."],
    adjElev: ["HØJDEJUSTERING", "Kikkertens højdetårn (MOA/MIL). Positiv = løbet peger højere = træfpunktet stiger."],
    adjWind: ["SIDEJUSTERING", "Kikkertens sidetårn. Positiv = træfpunktet flytter til højre."],
    targetDist: ["MÅLAFSTAND", "Afstand til målet målt langs sigtelinjen."],
    incline: ["HÆLDNINGSVINKEL", "Op-/nedadgående skud. Tyngdekraften virker kun på den vandrette komponent: skrå skud rammer højt."],
    wind: ["VIND", "Hastighed og klokkeretning vinden blæser FRA (12 = fra målet). Sidevind driver kuglen; mod-/medvind ændrer lidt."],
    temp: ["TEMPERATUR", "Varm luft er tyndere: mindre modstand, fladere skud. Kold luft gør det modsatte."],
    pressure: ["LUFTTRYK", "Lavere stationstryk (større højde) = tyndere luft = mindre modstand."],
    humidity: ["LUFTFUGTIGHED", "Fugtig luft er en anelse MINDRE tæt end tør — en meget lille effekt."],
    lat: ["BREDDEGRAD", "Hvor på Jorden du skyder; skalerer Coriolis-afbøjningen."],
    az: ["SKUDAZIMUT", "Kompaskurs for skuddet (0 = nord). Mod øst løftes træfpunktet, mod vest sænkes det (Eötvös)."],
    spin: ["SPINDRIFT", "Gyroskopisk drift fra den roterende kugle — højrerifling driver mod højre og vokser med flyvetiden."],
    twist: ["RIFFELSTIGNING", "Én omgang på n tommer. Hurtigere stigning (mindre n): højere stabilitet (SG, Millers regel), men lidt mere spindrift. SG under 1,0 = ustabil kugle."],
    cor: ["CORIOLIS + EÖTVÖS", "Jordrotationseffekter: vandret drift (Coriolis) og lodret forskydning afhængigt af azimut (Eötvös)."],
    exag: ["VISNINGSTILSTAND", "REEL viser den sande geometri (1:1) — buen er næsten usynlig på afstand. BUE forstørrer afvigelsen fra sigtelinjen. Alle tal forbliver sande; kikkerten er altid 1:1."],
    sky: ["HIMMELLYS", "Kun scenens lysstyrke — ingen ballistisk effekt."],
    tgtSize: ["MÅLTYPE", "Fysisk mål på banen. Definerer ringe/zoner for point — kun visning og point, ingen ballistik."],
    theme: ["PANELER", "Lys/mørk for brugerfladen. 3D-scenen har sin egen kontakt nedenfor."],
    scene: ["SCENE", "Lys/mørk for 3D-banen — himmel, jord, markører. Uafhængig af panelerne; HIMMELLYS finjusterer stadig."],
  },
},
CS: {
  title: "VIRTUÁLNÍ STŘELNICE",
  legTraj: "DRÁHA STŘELY · PODLE RYCHLOSTI", legLos: "ZÁMĚRNÁ", legBore: "OSA HLAVNĚ", legGhost: "DUCH · PŘEDCHOZÍ VÝSTŘEL",
  modelBtn: "PŘEDPOKLADY MODELU", modelTitle: "MODEL",
  m: ["Hmotný bod (3-DOF) — bez vybočení a aerodynamického skoku", "Odpor: Cd(Mach) vzorového projektilu G1, škálováno 1/BC", "Hustota vzduchu ρ(T, P, RV) · rychlost zvuku a(T)", "Integrace: RK4 s Δt = 2 ms", "Úhel nástřelu řešen na rovné střelnici, použit na skloněný výstřel", "Derivace: Litzova aproximace, SG podle Millerova pravidla", "Coriolis: a = −2 Ω × v ze zeměpisné šířky + azimutu", "Scéna zveličuje odchylku od záměrné (puškohled je 1:1)", "Ráže ovlivňuje jen zobrazení — odpor nese BC"],
  mFoot: "VÝCVIKOVÁ VIZUALIZACE — NENÍ TO PALEBNÉ ŘEŠENÍ",
  atTarget: "NA CÍLI", dropL: "POKLES", driftL: "SNOS", velL: "RYCHLOST", energyL: "ENERGIE", tofL: "DOBA LETU", zerosL: "NULY", apexRo: "VRCHOL",
  targetFace: "TERČ", ringsNote: "KRUHY", noImpact: "ŽÁDNÝ ZÁSAH",
  tgtSizeL: "TYP TERČE", scoreL: "SKÓRE", hitTxt: "ZÁSAH", missTxt: "MINUTÍ", zoneTxt: function (z) { return "ZÓNA " + z; },
  tgtOpts: { ring50: "KRUHOVÝ TERČ · Ø 50 cm", ring100: "KRUHOVÝ TERČ · Ø 100 cm", gong30: "OCELOVÝ GONG · Ø 30 cm", ipsc: "PAPÍROVÝ IPSC · 45 × 57,5 cm", custom: "VLASTNÍ DESKA · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "VYGENEROVÁNO",
  fire: "PAL", devScale: "ZVĚTŠENÍ OBLOUKU", skyLbl: "JAS OBLOHY",
  paramsL: "PARAMETRY", dispL: "ZOBRAZENÍ",
  viewMode: "REŽIM POHLEDU", trueBtn: "REÁLNÝ", arcBtn: "OBLOUK", trueNote: "SKUTEČNÁ GEOMETRIE · 1:1",
  uiTheme: "PANELY", sceneTheme: "SCÉNA", darkBtn: "TMAVÝ", lightBtn: "SVĚTLÝ",
  cams: { side: "BOK", top: "SHORA", shooter: "STŘELEC", scope: "PUŠKOHLED", free: "ORBITA", rifle: "PUŠKA" },
  ammo: "STŘELIVO", rifle: "PUŠKA A OPTIKA", shotSec: "VÝSTŘEL", envSec: "PROSTŘEDÍ", advSec: "POKROČILÉ", dopeSec: "TABULKA DOPE",
  custom: "Vlastní", tgtLbl: "CÍL", windLbl: "VÍTR", tgtRow: "CÍL",
  mvL: "ÚSŤOVÁ RYCHLOST", massL: "HMOTNOST STŘELY", bcL: "BALISTICKÝ KOEF. · G1", calL: "RÁŽE", barrelL: "DÉLKA HLAVNĚ",
  scopeHL: "VÝŠKA PUŠKOHLEDU NAD HLAVNÍ", zeroL: "NÁSTŘELNÁ VZDÁLENOST", cantL: "NÁKLON · + = VPRAVO", elevL: "VÝŠKOVÁ KOREKCE", windAdjL: "STRANOVÁ KOREKCE",
  railL: "SKLON LIŠTY (ZÁKLADNA)", mountL: "SKLON MONTÁŽE (KROUŽKY)",
  tgtDistL: "VZDÁLENOST CÍLE", inclineL: "ÚHEL SKLONU",
  tempL: "TEPLOTA", pressL: "TLAK", humL: "VLHKOST",
  spinLbl: "DERIVACE · PRAVOTOČIVÝ VÝVRT (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "ZEMĚPISNÁ ŠÍŘKA", azL: "AZIMUT VÝSTŘELU · 0=S",
  twistL: "STOUPÁNÍ VÝVRTU", trainBtn: "TRÉNINKOVÝ REŽIM", trainTitle: "TRÉNINK", roundL: "KOLO", totalL: "CELKEM", ptsL: "B", nextBtn: "DALŠÍ KOLO ▸", exitBtn: "UKONČIT",
  trainHint: "Podmínky náhodně vylosovány — přečti vítr, vzdálenost a teplotu, nastav věžičky a PAL.",
  trainHit: function (p) { return "+" + p + " B"; },
  dRng: "VZD", dDrop: "POKLES cm", dDrift: "SNOS cm", dTof: "ČAS",
  calm: "BEZVĚTŘÍ", fromClock: function (h) { return "OD " + h + " HODIN"; }, driftsL: "SNOS DOLEVA", driftsR: "SNOS DOPRAVA", headTail: "ČELNÍ/ZADNÍ",
  groundWarn: function (x) { return "⚠ STŘELA DOPADÁ NA ZEM V " + x + " — PŘED CÍLEM"; },
  scaleNote: function (n) { return "ODCHYLKA OD ZÁMĚRNÉ ×" + n; }, scopeNote: "POHLED PUŠKOHLEDEM · MĚŘÍTKO 1:1",
  firingLine: "PALEBNÁ ČÁRA", wind: "VÍTR", near: "BLÍZKÁ NULA", far: "VZDÁLENÁ NULA", apex: "VRCHOL", transonic: "TRANSSONIKA", ground: "ZEM", impact: "ZÁSAH", low: "NÍZKO", high: "VYSOKO", rr: "P", ll: "L",
  infoHint: "Najeď kurzorem na parametr a zobrazí se vysvětlení.",
  info: {
    preset: ["NÁBOJ (PŘEDVOLBA)", "Tovární laborace (rychlost, hmotnost, BC, ráže). Pohyb libovolným posuvníkem střeliva přepne na Vlastní."],
    mv: ["ÚSŤOVÁ RYCHLOST", "Rychlost střely na ústí hlavně. Vyšší rychlost = plošší dráha, kratší let, více energie."],
    massGr: ["HMOTNOST STŘELY", "Hmotnost v grainech (1 gr = 64,8 mg). Určuje energii; chování odporu popisuje BC."],
    bc: ["BALISTICKÝ KOEFICIENT (G1)", "Jak dobře střela překonává odpor vůči vzoru G1. Vyšší BC = plošší dráha a menší snos větrem."],
    cal: ["RÁŽE", "Průměr střely. Zde jen kosmetická — aerodynamický efekt už obsahuje BC."],
    barrelLen: ["DÉLKA HLAVNĚ", "Delší hlaveň spálí více prachu před opuštěním střely a zvýší rychlost (~6,1 m/s na palec, ref. 20\"). Lineární aproximace; nemění BC."],
    scopeH: ["VÝŠKA PUŠKOHLEDU", "Svislá vzdálenost mezi osou hlavně a osou puškohledu. Proto střela protíná záměrnou dvakrát (blízká a vzdálená nula)."],
    zeroDist: ["NÁSTŘELNÁ VZDÁLENOST", "Vzdálenost, kde se dráha a záměrná protínají. Určuje náměr hlavně."],
    railMoa: ["SKLON LIŠTY", "Pevný sklon základny (např. 20 MOA). Zde nekompenzován: zvedá zásah, dokud věžičku nestočíš zpět."],
    mountMoa: ["SKLON MONTÁŽE", "Dodatečný sklon stavitelných kroužků, přičtený k liště."],
    cant: ["NÁKLON", "Puška otočená kolem záměrné. Naklání vestavěný náměr do strany: zásahy jdou nízko a ve směru náklonu."],
    adjElev: ["VÝŠKOVÁ KOREKCE", "Výšková věžička (MOA/MIL). Kladná = hlaveň míří výš = zásah stoupá."],
    adjWind: ["STRANOVÁ KOREKCE", "Stranová věžička. Kladná = zásah se posouvá doprava."],
    targetDist: ["VZDÁLENOST CÍLE", "Vzdálenost k cíli měřená podél záměrné."],
    incline: ["ÚHEL SKLONU", "Střelba do kopce/z kopce. Gravitace působí jen na vodorovnou složku: skloněné výstřely zasahují výš."],
    wind: ["VÍTR", "Rychlost a hodinový směr, ODKUD fouká (12 = od cíle). Boční vítr střelu snáší; čelní/zadní mění málo."],
    temp: ["TEPLOTA", "Teplý vzduch je řidší: menší odpor, plošší výstřel. Studený naopak."],
    pressure: ["TLAK", "Nižší staniční tlak (vyšší nadmořská výška) = řidší vzduch = menší odpor."],
    humidity: ["VLHKOST", "Vlhký vzduch je nepatrně MÉNĚ hustý než suchý — velmi malý efekt."],
    lat: ["ZEMĚPISNÁ ŠÍŘKA", "Kde na Zemi střílíš; škáluje Coriolisovu výchylku."],
    az: ["AZIMUT VÝSTŘELU", "Kompasový směr výstřelu (0 = sever). Střelba na východ zásah zvedá, na západ snižuje (Eötvös)."],
    spin: ["DERIVACE", "Gyroskopický snos rotující střely — pravotočivý vývrt snáší doprava, roste s dobou letu."],
    twist: ["STOUPÁNÍ VÝVRTU", "Jedna otáčka na n palců. Rychlejší stoupání (menší n): vyšší stabilita (SG, Millerovo pravidlo), ale o něco větší derivace. SG pod 1,0 = nestabilní střela."],
    cor: ["CORIOLIS + EÖTVÖS", "Efekty rotace Země: vodorovný snos (Coriolis) a svislý posun podle azimutu (Eötvös)."],
    exag: ["REŽIM POHLEDU", "REÁLNÝ ukazuje skutečnou geometrii (1:1) — oblouk je na dálku téměř neviditelný. OBLOUK zvětšuje odchylku od záměrné. Čísla zůstávají pravdivá; puškohled je vždy 1:1."],
    sky: ["JAS OBLOHY", "Pouze jas scény — bez balistického vlivu."],
    tgtSize: ["TYP TERČE", "Fyzický terč na stanovišti. Určuje kruhy/zóny pro bodování — jen vzhled a skóre, žádná balistika."],
    theme: ["PANELY", "Světlý/tmavý vzhled rozhraní. 3D scéna má vlastní přepínač níže."],
    scene: ["SCÉNA", "Světlá/tmavá 3D střelnice — obloha, zem, značky. Nezávisle na panelech; JAS OBLOHY dál dolaďuje."],
  },
},
});
