window.VSR_LANGS = Object.assign(window.VSR_LANGS || {}, {
IT: {
  title: "POLIGONO DI TIRO VIRTUALE",
  legTraj: "TRAIETTORIA · PER VELOCITÀ", legLos: "LINEA DI MIRA", legBore: "ASSE DELLA CANNA", legGhost: "FANTASMA · TIRO PRECEDENTE",
  modelBtn: "IPOTESI DEL MODELLO", modelTitle: "MODELLO",
  m: ["Massa puntiforme (3-DOF) — senza imbardata né salto aerodinamico", "Resistenza: Cd(Mach) del proiettile campione G1, scalato per 1/BC", "Densità dell'aria ρ(T, P, UR) · velocità del suono a(T)", "Integrazione: RK4 con Δt = 2 ms", "Angolo di zero risolto su poligono piano, applicato al tiro inclinato", "Deriva giroscopica: approssimazione di Litz, SG con regola di Miller", "Coriolis: a = −2 Ω × v da latitudine + azimut", "La scena esagera lo scarto dalla linea di mira (ottica in scala 1:1)", "Il calibro incide solo sulla grafica — la resistenza è nel BC"],
  mFoot: "VISUALIZZAZIONE ADDESTRATIVA — NON È UNA SOLUZIONE DI TIRO",
  atTarget: "SUL BERSAGLIO", dropL: "CADUTA", driftL: "DERIVA", velL: "VELOCITÀ", energyL: "ENERGIA", tofL: "TEMPO DI VOLO", zerosL: "ZERI", apexRo: "APICE",
  targetFace: "BERSAGLIO", ringsNote: "ANELLI", noImpact: "NESSUN IMPATTO",
  tgtSizeL: "TIPO DI BERSAGLIO", scoreL: "PUNTEGGIO", hitTxt: "COLPITO", missTxt: "MANCATO", zoneTxt: function (z) { return "ZONA " + z; },
  tgtOpts: { ring50: "BERSAGLIO AD ANELLI · Ø 50 cm", ring100: "BERSAGLIO AD ANELLI · Ø 100 cm", gong30: "GONG D'ACCIAIO · Ø 30 cm", ipsc: "CARTA IPSC · 45 × 57,5 cm", custom: "PIASTRA PERSONALE · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GENERATO",
  fire: "FUOCO", devScale: "INGRANDIMENTO DELL'ARCO", skyLbl: "LUCE DEL CIELO",
  paramsL: "PARAMETRI", dispL: "SCHERMO",
  viewMode: "MODALITÀ VISTA", trueBtn: "REALE", arcBtn: "ARCO", trueNote: "GEOMETRIA REALE · 1:1",
  uiTheme: "PANNELLI", sceneTheme: "SCENA", darkBtn: "SCURO", lightBtn: "CHIARO",
  cams: { side: "LATO", top: "ALTO", shooter: "TIRATORE", scope: "OTTICA", free: "ORBITA", rifle: "CARABINA" },
  ammo: "MUNIZIONI", rifle: "CARABINA E OTTICA", shotSec: "TIRO", envSec: "AMBIENTE", advSec: "AVANZATE", dopeSec: "TABELLA DOPE",
  custom: "Personale", tgtLbl: "BERS", windLbl: "VENTO", tgtRow: "BERS",
  mvL: "VELOCITÀ INIZIALE", massL: "MASSA DELLA PALLA", bcL: "COEFF. BALISTICO · G1", calL: "CALIBRO", barrelL: "LUNGHEZZA CANNA",
  scopeHL: "ALTEZZA OTTICA SULLA CANNA", zeroL: "DISTANZA DI ZERO", cantL: "CANT · + = DESTRA", elevL: "CORREZIONE VERTICALE", windAdjL: "CORREZIONE LATERALE",
  railL: "INCLINAZIONE SLITTA (BASE)", mountL: "INCLINAZIONE ATTACCHI",
  tgtDistL: "DISTANZA DEL BERSAGLIO", inclineL: "ANGOLO DI SITO",
  tempL: "TEMPERATURA", pressL: "PRESSIONE", humL: "UMIDITÀ",
  spinLbl: "DERIVA GIRO. · RIGATURA DESTRA (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "LATITUDINE", azL: "AZIMUT DEL TIRO · 0=N",
  twistL: "PASSO DI RIGATURA", trainBtn: "MODALITÀ ALLENAMENTO", trainTitle: "ALLENAMENTO", roundL: "TURNO", totalL: "TOTALE", ptsL: "PTI", nextBtn: "PROSSIMO TURNO ▸", exitBtn: "ESCI",
  trainHint: "Condizioni casuali — leggi vento, distanza e temperatura, regola le torrette, poi FUOCO.",
  trainHit: function (p) { return "+" + p + " PTI"; },
  dRng: "DST", dDrop: "CAD cm", dDrift: "DER cm", dTof: "TDV",
  calm: "CALMA", fromClock: function (h) { return "DA ORE " + h; }, driftsL: "DERIVA A SINISTRA", driftsR: "DERIVA A DESTRA", headTail: "FRONTALE/IN CODA",
  groundWarn: function (x) { return "⚠ LA PALLA TOCCA TERRA A " + x + " — PRIMA DEL BERSAGLIO"; },
  scaleNote: function (n) { return "SCARTO DALLA LINEA DI MIRA ×" + n; }, scopeNote: "VISTA OTTICA · SCALA 1:1",
  firingLine: "LINEA DI TIRO", wind: "VENTO", near: "ZERO VICINO", far: "ZERO LONTANO", apex: "APICE", transonic: "TRANSONICO", ground: "TERRENO", impact: "IMPATTO", low: "BASSO", high: "ALTO", rr: "D", ll: "S",
  infoHint: "Passa il mouse su un parametro per vederne la spiegazione.",
  info: {
    preset: ["CARTUCCIA (PRESET)", "Cariche di fabbrica (velocità, massa, BC, calibro). Muovere un cursore delle munizioni passa a Personale."],
    mv: ["VELOCITÀ INIZIALE", "Velocità della palla alla volata. Più velocità = arco più teso, volo più breve, più energia."],
    massGr: ["MASSA DELLA PALLA", "Massa in grani (1 gr = 64,8 mg). Determina l'energia; il comportamento aerodinamico è nel BC."],
    bc: ["COEFFICIENTE BALISTICO (G1)", "Quanto la palla vince la resistenza rispetto al campione G1. BC più alto = traiettoria più tesa e meno deriva dal vento."],
    cal: ["CALIBRO", "Diametro della palla. Qui solo estetico — l'effetto aerodinamico è già nel BC."],
    barrelLen: ["LUNGHEZZA CANNA", "Una canna più lunga brucia più polvere prima dell'uscita, aumentando la velocità (~6,1 m/s per pollice, rif. 20\"). Approssimazione lineare; non cambia il BC."],
    scopeH: ["ALTEZZA OTTICA", "Distanza verticale tra asse della canna e asse dell'ottica. Per questo la palla incrocia la linea di mira due volte (zero vicino e lontano)."],
    zeroDist: ["DISTANZA DI ZERO", "Distanza a cui traiettoria e linea di mira si incrociano. Definisce l'alzo della canna."],
    railMoa: ["INCLINAZIONE SLITTA", "Inclinazione fissa della base (es. 20 MOA). Compensata all'azzeramento: l'impatto resta sul punto mirato; libera solo corsa extra della torretta per le lunghe distanze."],
    mountMoa: ["INCLINAZIONE ATTACCHI", "Inclinazione aggiuntiva degli attacchi regolabili, sommata alla slitta."],
    cant: ["CANT", "Carabina ruotata attorno alla linea di mira. Inclina l'alzo integrato: i colpi vanno bassi e verso il lato inclinato."],
    adjElev: ["CORREZIONE VERTICALE", "Torretta di elevazione (MOA/MIL). Positiva = canna più alta = impatto più in alto."],
    adjWind: ["CORREZIONE LATERALE", "Torretta di deriva. Positiva = impatto verso destra."],
    targetDist: ["DISTANZA DEL BERSAGLIO", "Distanza dal bersaglio misurata lungo la linea di mira."],
    incline: ["ANGOLO DI SITO", "Tiro in salita/discesa. La gravità agisce solo sulla componente orizzontale: i tiri inclinati colpiscono alto."],
    wind: ["VENTO", "Velocità e direzione a orologio DA CUI soffia (12 = dal bersaglio). Il vento laterale sposta la palla; frontale/in coda cambia poco."],
    temp: ["TEMPERATURA", "L'aria calda è più rarefatta: meno resistenza, tiro più teso. L'aria fredda fa l'opposto."],
    pressure: ["PRESSIONE", "Pressione più bassa (quota maggiore) = aria più rarefatta = meno resistenza."],
    humidity: ["UMIDITÀ", "L'aria umida è leggermente MENO densa di quella secca — effetto molto piccolo."],
    lat: ["LATITUDINE", "Dove spari sulla Terra; scala la deviazione di Coriolis."],
    az: ["AZIMUT DEL TIRO", "Direzione bussola del tiro (0 = nord). Verso est alza l'impatto, verso ovest lo abbassa (Eötvös)."],
    spin: ["DERIVA GIROSCOPICA", "Deriva della palla in rotazione — rigatura destra deriva a destra, cresce col tempo di volo."],
    twist: ["PASSO DI RIGATURA", "Un giro in n pollici. Passo più rapido (n minore): più stabilità (SG, regola di Miller) ma un po' più deriva. SG sotto 1,0 = palla instabile."],
    cor: ["CORIOLIS + EÖTVÖS", "Effetti della rotazione terrestre: deriva orizzontale (Coriolis) e spostamento verticale legato all'azimut (Eötvös)."],
    exag: ["MODALITÀ VISTA", "REALE mostra la geometria 1:1 — l'arco è quasi invisibile a distanza. ARCO ingrandisce lo scarto dalla linea di mira. I numeri restano veri; l'ottica è sempre 1:1."],
    sky: ["LUCE DEL CIELO", "Solo luminosità della scena — nessun effetto balistico."],
    tgtSize: ["TIPO DI BERSAGLIO", "Bersaglio fisico in linea. Definisce anelli/zone per il punteggio — solo grafica e punteggio, niente balistica."],
    theme: ["PANNELLI", "Chiaro/scuro per l'interfaccia. La scena 3D ha un interruttore separato sotto."],
    scene: ["SCENA", "Chiaro/scuro per il poligono 3D — cielo, terreno, marcatori. Indipendente dai pannelli; LUCE DEL CIELO regola ancora."],
  },
},
PT: {
  title: "CARREIRA DE TIRO VIRTUAL",
  legTraj: "TRAJETÓRIA · POR VELOCIDADE", legLos: "LINHA DE MIRA", legBore: "EIXO DO CANO", legGhost: "FANTASMA · TIRO ANTERIOR",
  modelBtn: "PREMISSAS DO MODELO", modelTitle: "MODELO",
  m: ["Massa pontual (3-DOF) — sem guinada nem salto aerodinâmico", "Arrasto: Cd(Mach) do projétil padrão G1, escalado por 1/BC", "Densidade do ar ρ(T, P, UR) · velocidade do som a(T)", "Integração: RK4 com Δt = 2 ms", "Ângulo de zero resolvido em pista plana, aplicado ao tiro inclinado", "Deriva giroscópica: aproximação de Litz, SG pela regra de Miller", "Coriolis: a = −2 Ω × v de latitude + azimute", "A cena exagera o desvio da linha de mira (luneta em escala 1:1)", "O calibre afeta só a imagem — o arrasto está no BC"],
  mFoot: "VISUALIZAÇÃO DE TREINO — NÃO É UMA SOLUÇÃO DE TIRO",
  atTarget: "NO ALVO", dropL: "QUEDA", driftL: "DERIVA", velL: "VELOCIDADE", energyL: "ENERGIA", tofL: "TEMPO DE VOO", zerosL: "ZEROS", apexRo: "ÁPICE",
  targetFace: "ALVO", ringsNote: "ANÉIS", noImpact: "SEM IMPACTO",
  tgtSizeL: "TIPO DE ALVO", scoreL: "PONTUAÇÃO", hitTxt: "ACERTO", missTxt: "ERRO", zoneTxt: function (z) { return "ZONA " + z; },
  tgtOpts: { ring50: "ALVO DE ANÉIS · Ø 50 cm", ring100: "ALVO DE ANÉIS · Ø 100 cm", gong30: "GONGO DE AÇO · Ø 30 cm", ipsc: "PAPEL IPSC · 45 × 57,5 cm", custom: "CHAPA PERSONALIZADA · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GERADO",
  fire: "FOGO", devScale: "AMPLIAÇÃO DO ARCO", skyLbl: "LUZ DO CÉU",
  paramsL: "PARÂMETROS", dispL: "ECRÃ",
  viewMode: "MODO DE VISTA", trueBtn: "REAL", arcBtn: "ARCO", trueNote: "GEOMETRIA REAL · 1:1",
  uiTheme: "PAINÉIS", sceneTheme: "CENA", darkBtn: "ESCURO", lightBtn: "CLARO",
  cams: { side: "LADO", top: "TOPO", shooter: "ATIRADOR", scope: "LUNETA", free: "ÓRBITA", rifle: "ESPINGARDA" },
  ammo: "MUNIÇÃO", rifle: "ESPINGARDA E ÓTICA", shotSec: "TIRO", envSec: "AMBIENTE", advSec: "AVANÇADO", dopeSec: "TABELA DOPE",
  custom: "Personalizada", tgtLbl: "ALVO", windLbl: "VENTO", tgtRow: "ALVO",
  mvL: "VELOCIDADE INICIAL", massL: "MASSA DO PROJÉTIL", bcL: "COEF. BALÍSTICO · G1", calL: "CALIBRE", barrelL: "COMPRIMENTO DO CANO",
  scopeHL: "ALTURA DA LUNETA", zeroL: "DISTÂNCIA DE ZERO", cantL: "INCLINAÇÃO LATERAL · + = DIREITA", elevL: "AJUSTE VERTICAL", windAdjL: "AJUSTE LATERAL",
  railL: "INCLINAÇÃO DO TRILHO (BASE)", mountL: "INCLINAÇÃO DAS MONTAGENS",
  tgtDistL: "DISTÂNCIA DO ALVO", inclineL: "ÂNGULO DE INCLINAÇÃO",
  tempL: "TEMPERATURA", pressL: "PRESSÃO", humL: "HUMIDADE",
  spinLbl: "DERIVA GIRO. · ESTRIA DIREITA (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "LATITUDE", azL: "AZIMUTE DO TIRO · 0=N",
  twistL: "PASSO DE ESTRIA", trainBtn: "MODO DE TREINO", trainTitle: "TREINO", roundL: "RONDA", totalL: "TOTAL", ptsL: "PTS", nextBtn: "PRÓXIMA RONDA ▸", exitBtn: "SAIR",
  trainHint: "Condições aleatórias — lê o vento, a distância e a temperatura, ajusta as torres e dispara.",
  trainHit: function (p) { return "+" + p + " PTS"; },
  dRng: "DST", dDrop: "QUEDA cm", dDrift: "DER cm", dTof: "TDV",
  calm: "CALMO", fromClock: function (h) { return "DAS " + h + " HORAS"; }, driftsL: "DERIVA À ESQUERDA", driftsR: "DERIVA À DIREITA", headTail: "FRONTAL/TRASEIRO",
  groundWarn: function (x) { return "⚠ O PROJÉTIL ATINGE O SOLO A " + x + " — ANTES DO ALVO"; },
  scaleNote: function (n) { return "DESVIO DA LINHA DE MIRA ×" + n; }, scopeNote: "VISTA DA LUNETA · ESCALA 1:1",
  firingLine: "LINHA DE FOGO", wind: "VENTO", near: "ZERO PRÓXIMO", far: "ZERO DISTANTE", apex: "ÁPICE", transonic: "TRANSÓNICO", ground: "SOLO", impact: "IMPACTO", low: "BAIXO", high: "ALTO", rr: "D", ll: "E",
  infoHint: "Passa o cursor sobre um parâmetro para ver a explicação.",
  info: {
    preset: ["CARTUCHO (PRESET)", "Cargas de fábrica (velocidade, massa, BC, calibre). Mover qualquer controlo de munição muda para Personalizada."],
    mv: ["VELOCIDADE INICIAL", "Velocidade do projétil à boca do cano. Mais velocidade = arco mais tenso, voo mais curto, mais energia."],
    massGr: ["MASSA DO PROJÉTIL", "Massa em grãos (1 gr = 64,8 mg). Define a energia; o comportamento de arrasto vem do BC."],
    bc: ["COEFICIENTE BALÍSTICO (G1)", "Quão bem o projétil vence o arrasto face ao padrão G1. BC maior = trajetória mais tensa e menos deriva pelo vento."],
    cal: ["CALIBRE", "Diâmetro do projétil. Aqui apenas cosmético — o efeito aerodinâmico já está no BC."],
    barrelLen: ["COMPRIMENTO DO CANO", "Um cano mais longo queima mais pólvora antes da saída, aumentando a velocidade (~6,1 m/s por polegada, ref. 20\"). Aproximação linear; não muda o BC."],
    scopeH: ["ALTURA DA LUNETA", "Distância vertical entre o eixo do cano e o da luneta. Por isso o projétil cruza a linha de mira duas vezes (zero próximo e distante)."],
    zeroDist: ["DISTÂNCIA DE ZERO", "Distância onde a trajetória e a linha de mira se cruzam. Define a elevação do cano."],
    railMoa: ["INCLINAÇÃO DO TRILHO", "Inclinação fixa da base (p. ex. 20 MOA). Compensada ao zerar: o impacto fica no ponto visado; apenas liberta curso extra de elevação para longa distância."],
    mountMoa: ["INCLINAÇÃO DAS MONTAGENS", "Inclinação adicional das montagens reguláveis, somada ao trilho."],
    cant: ["INCLINAÇÃO LATERAL", "Espingarda rodada em torno da linha de mira. Inclina a elevação integrada: os tiros saem baixos e para o lado inclinado."],
    adjElev: ["AJUSTE VERTICAL", "Torre de elevação (MOA/MIL). Positivo = cano mais alto = impacto sobe."],
    adjWind: ["AJUSTE LATERAL", "Torre de deriva. Positivo = impacto move-se para a direita."],
    targetDist: ["DISTÂNCIA DO ALVO", "Distância ao alvo medida ao longo da linha de mira."],
    incline: ["ÂNGULO DE INCLINAÇÃO", "Tiro a subir/descer. A gravidade age só na componente horizontal: tiros inclinados acertam alto."],
    wind: ["VENTO", "Velocidade e direção horária DE ONDE sopra (12 = do alvo). Vento cruzado desvia o projétil; frontal/traseiro muda pouco."],
    temp: ["TEMPERATURA", "Ar quente é mais rarefeito: menos arrasto, tiro mais tenso. Ar frio faz o contrário."],
    pressure: ["PRESSÃO", "Pressão mais baixa (maior altitude) = ar mais rarefeito = menos arrasto."],
    humidity: ["HUMIDADE", "Ar húmido é ligeiramente MENOS denso que ar seco — efeito muito pequeno."],
    lat: ["LATITUDE", "Onde disparas na Terra; escala o desvio de Coriolis."],
    az: ["AZIMUTE DO TIRO", "Rumo de bússola do tiro (0 = norte). Para leste sobe o impacto, para oeste desce (Eötvös)."],
    spin: ["DERIVA GIROSCÓPICA", "Deriva do projétil em rotação — estria direita deriva à direita, cresce com o tempo de voo."],
    twist: ["PASSO DE ESTRIA", "Uma volta em n polegadas. Passo mais rápido (n menor): mais estabilidade (SG, regra de Miller) mas um pouco mais de deriva. SG abaixo de 1,0 = projétil instável."],
    cor: ["CORIOLIS + EÖTVÖS", "Efeitos da rotação da Terra: deriva horizontal (Coriolis) e deslocamento vertical conforme o azimute (Eötvös)."],
    exag: ["MODO DE VISTA", "REAL mostra a geometria 1:1 — o arco é quase invisível à distância. ARCO amplia o desvio da linha de mira. Os números continuam verdadeiros; a luneta é sempre 1:1."],
    sky: ["LUZ DO CÉU", "Apenas brilho da cena — sem efeito balístico."],
    tgtSize: ["TIPO DE ALVO", "Alvo físico na linha. Define anéis/zonas para pontuar — só imagem e pontuação, sem balística."],
    theme: ["PAINÉIS", "Claro/escuro para a interface. A cena 3D tem o seu próprio interruptor abaixo."],
    scene: ["CENA", "Claro/escuro para a carreira 3D — céu, solo, marcadores. Independente dos painéis; LUZ DO CÉU continua a afinar."],
  },
},
NL: {
  title: "VIRTUELE SCHIETBAAN",
  legTraj: "BAAN · OP SNELHEID", legLos: "RICHTLIJN", legBore: "LOOPAS", legGhost: "GEEST · VORIG SCHOT",
  modelBtn: "MODELAANNAMES", modelTitle: "MODEL",
  m: ["Puntmassa (3-DOF) — geen gieren, geen aerodynamische sprong", "Weerstand: G1-standaardprojectiel Cd(Mach), geschaald met 1/BC", "Luchtdichtheid ρ(T, P, RV) · geluidssnelheid a(T)", "Integratie: RK4 met Δt = 2 ms", "Nulhoek opgelost op vlakke baan, toegepast op hellend schot", "Spindrift: Litz-benadering, SG via Miller-regel", "Coriolis: a = −2 Ω × v uit breedtegraad + azimut", "De scène overdrijft de afwijking van de richtlijn (kijker op schaal 1:1)", "Kaliber beïnvloedt alleen de weergave — de weerstand zit in de BC"],
  mFoot: "TRAININGSVISUALISATIE — GEEN VUUROPLOSSING",
  atTarget: "OP DOEL", dropL: "VAL", driftL: "DRIFT", velL: "SNELHEID", energyL: "ENERGIE", tofL: "VLIEGTIJD", zerosL: "NULPUNTEN", apexRo: "TOP",
  targetFace: "SCHIETSCHIJF", ringsNote: "RINGEN", noImpact: "GEEN INSLAG",
  tgtSizeL: "DOELTYPE", scoreL: "SCORE", hitTxt: "RAAK", missTxt: "MIS", zoneTxt: function (z) { return "ZONE " + z; },
  tgtOpts: { ring50: "RINGSCHIJF · Ø 50 cm", ring100: "RINGSCHIJF · Ø 100 cm", gong30: "STALEN GONG · Ø 30 cm", ipsc: "IPSC-PAPIER · 45 × 57,5 cm", custom: "EIGEN PLAAT · Ø" },
  pdfBtn: "⎙ PDF", pdfPrinted: "GEGENEREERD",
  fire: "VUUR", devScale: "BOOGVERGROTING", skyLbl: "HEMELLICHT",
  paramsL: "PARAMETERS", dispL: "WEERGAVE",
  viewMode: "WEERGAVEMODUS", trueBtn: "ECHT", arcBtn: "BOOG", trueNote: "ECHTE GEOMETRIE · 1:1",
  uiTheme: "PANELEN", sceneTheme: "SCÈNE", darkBtn: "DONKER", lightBtn: "LICHT",
  cams: { side: "ZIJKANT", top: "BOVEN", shooter: "SCHUTTER", scope: "KIJKER", free: "ORBIT", rifle: "GEWEER" },
  ammo: "MUNITIE", rifle: "GEWEER & OPTIEK", shotSec: "SCHOT", envSec: "OMGEVING", advSec: "GEAVANCEERD", dopeSec: "DOPE-KAART",
  custom: "Eigen", tgtLbl: "DOEL", windLbl: "WIND", tgtRow: "DOEL",
  mvL: "MONDINGSSNELHEID", massL: "KOGELMASSA", bcL: "BALLISTISCHE COËFF. · G1", calL: "KALIBER", barrelL: "LOOPLENGTE",
  scopeHL: "KIJKERHOOGTE BOVEN LOOP", zeroL: "INSCHIETAFSTAND", cantL: "KANTELING · + = RECHTS", elevL: "HOOGTECORRECTIE", windAdjL: "ZIJCORRECTIE",
  railL: "RAILHELLING (BASIS)", mountL: "MONTAGEHELLING (RINGEN)",
  tgtDistL: "DOELAFSTAND", inclineL: "HELLINGSHOEK",
  tempL: "TEMPERATUUR", pressL: "LUCHTDRUK", humL: "VOCHTIGHEID",
  spinLbl: "SPINDRIFT · RECHTSE TREK (LITZ)", corLbl: "CORIOLIS + EÖTVÖS", latL: "BREEDTEGRAAD", azL: "SCHOTAZIMUT · 0=N",
  twistL: "SPOED", trainBtn: "TRAININGSMODUS", trainTitle: "TRAINING", roundL: "RONDE", totalL: "TOTAAL", ptsL: "PTN", nextBtn: "VOLGENDE RONDE ▸", exitBtn: "STOPPEN",
  trainHint: "Omstandigheden willekeurig — lees wind, afstand en temperatuur, stel je torens in en VUUR.",
  trainHit: function (p) { return "+" + p + " PTN"; },
  dRng: "AFS", dDrop: "VAL cm", dDrift: "DRF cm", dTof: "TVD",
  calm: "WINDSTIL", fromClock: function (h) { return "VAN " + h + " UUR"; }, driftsL: "DRIFT NAAR LINKS", driftsR: "DRIFT NAAR RECHTS", headTail: "TEGEN-/RUGWIND",
  groundWarn: function (x) { return "⚠ KOGEL RAAKT DE GROND OP " + x + " — VÓÓR HET DOEL"; },
  scaleNote: function (n) { return "AFWIJKING VAN DE RICHTLIJN ×" + n; }, scopeNote: "KIJKERBEELD · SCHAAL 1:1",
  firingLine: "VUURLIJN", wind: "WIND", near: "NABIJ NUL", far: "VER NUL", apex: "TOP", transonic: "TRANSSONISCH", ground: "GROND", impact: "INSLAG", low: "LAAG", high: "HOOG", rr: "R", ll: "L",
  infoHint: "Beweeg de muis over een parameter om de uitleg te zien.",
  info: {
    preset: ["PATROON-PRESET", "Fabriekladingen (snelheid, massa, BC, kaliber). Elke munitieschuif verzet schakelt naar Eigen."],
    mv: ["MONDINGSSNELHEID", "Kogelsnelheid aan de monding. Meer snelheid = vlakkere baan, kortere vliegtijd, meer energie."],
    massGr: ["KOGELMASSA", "Massa in grains (1 gr = 64,8 mg). Bepaalt de energie; het weerstandsgedrag zit in de BC."],
    bc: ["BALLISTISCHE COËFFICIËNT (G1)", "Hoe goed de kogel weerstand overwint t.o.v. het G1-standaardprojectiel. Hogere BC = vlakkere baan, minder winddrift."],
    cal: ["KALIBER", "Kogeldiameter. Hier cosmetisch — het aerodynamische effect zit al in de BC."],
    barrelLen: ["LOOPLENGTE", "Een langere loop verbrandt meer kruit vóór de monding en verhoogt de snelheid (~6,1 m/s per inch, ref. 20\"). Lineaire benadering; verandert de BC niet."],
    scopeH: ["KIJKERHOOGTE", "Verticale afstand tussen loopas en kijkeras. Daarom kruist de kogel de richtlijn twee keer (nabij en ver nul)."],
    zeroDist: ["INSCHIETAFSTAND", "Afstand waar baan en richtlijn elkaar kruisen. Bepaalt de opwaartse loophoek."],
    railMoa: ["RAILHELLING", "Vaste helling in de basis (bijv. 20 MOA). Gecompenseerd bij het inschieten: de inslag blijft op het richtpunt; het geeft alleen extra verstelbereik voor lange afstand."],
    mountMoa: ["MONTAGEHELLING", "Extra helling van verstelbare ringen, opgeteld bij de rail."],
    cant: ["KANTELING", "Geweer gerold om de richtlijn. Kantelt de ingebouwde elevatie opzij: schoten gaan laag en richting de kanteling."],
    adjElev: ["HOOGTECORRECTIE", "Elevatietoren (MOA/MIL). Positief = loop hoger = inslag stijgt."],
    adjWind: ["ZIJCORRECTIE", "Windagetoren. Positief = inslag naar rechts."],
    targetDist: ["DOELAFSTAND", "Afstand tot het doel gemeten langs de richtlijn."],
    incline: ["HELLINGSHOEK", "Berg op/af. Zwaartekracht werkt alleen op de horizontale component: hellende schoten raken hoog."],
    wind: ["WIND", "Snelheid en klokrichting WAARUIT de wind waait (12 = van het doel). Zijwind verdrijft de kogel; tegen-/rugwind verandert weinig."],
    temp: ["TEMPERATUUR", "Warme lucht is ijler: minder weerstand, vlakker schot. Koude lucht doet het omgekeerde."],
    pressure: ["LUCHTDRUK", "Lagere stationsdruk (grotere hoogte) = ijlere lucht = minder weerstand."],
    humidity: ["VOCHTIGHEID", "Vochtige lucht is iets MINDER dicht dan droge — een zeer klein effect."],
    lat: ["BREEDTEGRAAD", "Waar op aarde je schiet; schaalt de Coriolis-afwijking."],
    az: ["SCHOTAZIMUT", "Kompaskoers van het schot (0 = noord). Naar het oosten tilt de inslag op, naar het westen verlaagt hem (Eötvös)."],
    spin: ["SPINDRIFT", "Gyroscopische drift van de draaiende kogel — rechtse trek drift naar rechts, groeit met de vliegtijd."],
    twist: ["SPOED", "Eén omwenteling per n inch. Snellere spoed (kleinere n): hogere stabiliteit (SG, Miller-regel) maar iets meer spindrift. SG onder 1,0 = instabiele kogel."],
    cor: ["CORIOLIS + EÖTVÖS", "Aardrotatie-effecten: horizontale drift (Coriolis) en verticale verschuiving afhankelijk van azimut (Eötvös)."],
    exag: ["WEERGAVEMODUS", "ECHT toont de ware geometrie (1:1) — de boog is op afstand bijna onzichtbaar. BOOG vergroot de afwijking van de richtlijn. Alle getallen blijven waar; de kijker is altijd 1:1."],
    sky: ["HEMELLICHT", "Alleen scènehelderheid — geen ballistisch effect."],
    tgtSize: ["DOELTYPE", "Fysiek doel op de baan. Bepaalt ringen/zones voor de score — alleen weergave en score, geen ballistiek."],
    theme: ["PANELEN", "Licht/donker voor de interface. De 3D-scène heeft hieronder een eigen schakelaar."],
    scene: ["SCÈNE", "Licht/donker voor de 3D-baan — lucht, grond, markeringen. Onafhankelijk van de panelen; HEMELLICHT stemt verder af."],
  },
},
});
